# Name of dbt project
name: 'fetch-code-challenge'
version: '1.0.0'
profile: 'fetch_profile'  # Name of the dbt profile to use, configured in profiles.yml

# Define paths for models, tests, snapshots, and seeds
source-paths: ['models']
target-path: 'target'  # Compiled SQL files go here
clean-targets: ['target', 'dbt_modules']  # Folders that dbt will clean during dbt clean

# Optional - configure the path for seeds and snapshots
data-paths: ['data']  # Folder for CSV seeds if needed
snapshot-paths: ['snapshots']

# Configures how dbt interprets models, tests, and other resource files
model-paths: ['models']
test-paths: ['tests']

# Specify where compiled and run results are stored
analysis-paths: ['analyses']  # Custom SQL analyses
macro-paths: ['macros']       # Folder for custom macros
docs-paths: ['docs']

# Specify the default materialization (e.g., table, view) for models
models:
  fetch_project:
    +materialized: view  # Default materialization is view; can be overridden per model

# Setting up tests with configurations
tests:
  generic:
    +severity: warn  # Specifies test severity levels, e.g., warn or error
  - name: test_non_null_user_ids
  - name: test_negative_total_spent

# Configurations for seeds
seeds:
  fetch_project:
    +schema: seeds  # Schema where seeds will be loaded if you use any CSV data files

# Specify custom target environments (dev, prod) and schemas for models
target-path: "target"
profile: "fetch_profile"
config-version: 2

# Specify environment-specific settings
# Customize based on database setup, such as development and production environments
vars:
  environment: 'dev'  # This can be changed to 'prod' for production settings
